simulation:
  schedulers:
  - static
  #- dynamic_adab
  #- dynamic_acab
  - rl
  min_buoys: 10
  max_buoys: 40 #80
  step_buoys: 10
  intervals:
  - 1.0
  - 0.5
  - 0.25
  duration: 600
  num_processes: 4
  ideal_channel: true
  ramp_scenario: false
  enable_metrics: true
  enable_logging: false
  multihop_mode: none  # Options: none, append, forwarded
  multihop_limit: 2    # Maximum hops for forwarded mode
world:
  width: 800.0
  height: 800.0
buoys:
  mobile_percentage: 0.2
  default_battery: 100.0
  default_velocity: 15.0
network:
  bit_rate: 1000000
  speed_of_light: 300000000.0
  communication_range_max: 120.0
  communication_range_high_prob: 70.0
  delivery_prob_high: 0.9
  delivery_prob_low: 0.15
csma:
  slot_time: 2.0e-05
  difs_time: 5.0e-05
  cw: 16
  backoff_time_min: 0.001
  backoff_time_max: 0.016
scheduler:
  beacon_min_interval: 1.0
  beacon_max_interval: 5.0
  static_interval: 1.0
